---
- name: Install carbon-relay-ng
  apt: pkg=carbon-relay-ng state=present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: ansible_os_family == "Debian"

- name: Install carbon-relay-ng
  yum: pkg=carbon-relay-ng state=installed
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: ansible_os_family == "RedHat"

- name: Create carbon-relay-ng etc-dir
  file:
    path: /etc/carbon-relay-ng
    state: directory

- name: Install carbon-relay-ng configuration
  template:
    src: carbon-relay-ng.conf.j2
    dest: /etc/carbon-relay-ng/carbon-relay-ng.conf
  notify: restart carbon-relay-ng

- name: Add group !workaround!
  group:
    name: carbon-relay-ng
    system: true
  notify: restart carbon-relay-ng

- name: Add user !workaround!
  user:
    name: carbon-relay-ng
    group: carbon-relay-ng
    home: '{{ carbon_relay_ng_run_dir }}'
    shell: "/usr/sbin/nologin"
    system: true
  notify: restart carbon-relay-ng

- name: Chown carbon-relay-ng home
  file:
    path: '{{ carbon_relay_ng_run_dir }}'
    owner: carbon-relay-ng
  notify: restart carbon-relay-ng

- name: Create carbon-relay-ng home on boot
  copy:
    content: "D {{ carbon_relay_ng_run_dir }} 0755 carbon-relay-ng carbon-relay-ng"
    dest: "/etc/tmpfiles.d/carbon-relay-ng.conf"

- name: Create carbon-relay-ng spool-dir
  file:
    path: '{{ carbon_relay_ng_spool_dir }}'
    state: directory

- name: Chown carbon-relay-ng spool
  file:
    path: '{{ carbon_relay_ng_spool_dir }}'
    owner: carbon-relay-ng
  notify: restart carbon-relay-ng

- name: Ensure carbon-relay-ng is started and enabled on boot
  service:
    name: carbon-relay-ng
    state: started
    enabled: "{{ carbon_relay_ng_enabled_on_boot }}"
